### ISSUE TITLE
:bug: Les variables AUTHOR et EDITOR ignorées :lady_beetle: 

### ISSUE THREAD

**Issue by mbarre** [opt-nc/template-eae#13]
- [ ] ePub
- [ ] pdf

ces variables ne sont pas prises en compte lors de la génération du PDF

![image](https://user-images.githubusercontent.com/1823161/165645529-f5fce1c3-ee59-41f0-b151-c6c61314d3e3.png)

Alors que le fichier title.yml est complété :

![image](https://user-images.githubusercontent.com/1823161/165645585-26ec218e-5dc1-4f2b-b397-eca722281396.png)

**Comment by adriens** [comment]
Bug reproduit :+1:

**Comment by adriens** [comment]
# Pour le ePiub
 
Des ressources pour avancer sur le sujet : 

- `--epub-metadata` : [PANDOC MANUAL](https://www.uv.es/wikibase/doc/cas/pandoc_manual_2.7.3.wiki?170)

```yaml
---
title:
- type: main
  text: My Book
- type: subtitle
  text: An investigation of metadata
creator:
- role: author
  text: John Smith
- role: editor
  text: Sarah Jones
identifier:
- scheme: DOI
  text: doi:10.234234.234/33
publisher:  My Press
rights: © 2007 John Smith, CC BY-NC
ibooks:
  version: 1.3.4
...
```

Créer un fichier `metadatas.txt` puis : 

```shell
pandoc -o progit.epub metadatas.txt \
  01-introduction/01-chapter1.markdown...
```
