### ISSUE TITLE
Erreur sur le 'make all'

### ISSUE THREAD

**Issue by mbarre** [opt-nc/template-eae#15]
La target all ne fonctionne pas :
```shell
❯ make all
gitchangelog > gitlog.rst
pandoc gitlog.rst -f rst -t markdown -o gitlog.md
gh changelog new
✅ Open CHANGELOG.md or run 'gh changelog show' to view your changelog.
mv CHANGELOG.md release.md
sed -i 's/# Changelog/# Release/g' release.md
pandoc -t html --section-divs --standalone -o mon-EAE.html title.yml ressources.md 00_identification_agent.md 01_entete.md 02_resume.md 03_fiche-de-poste.md 04_tenue-maitrise-du-poste.md 05_appreciation_competences.md 06_autoevaluation.md 07_plan-action.md 08_evolution-professionnelle.md 09_synthese-evaluation.md 10_avancement.md release.md gitlog.md
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'title' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".

```

```yaml
---
title:
- type: main
  text: Mon EAE
- type: subtitle
  text: Préparation de l'EAE
creator:
- role: author
  text: Michèle BARRE
- role: editor
  text: Adrien SALES
identifier:
- scheme: 
  text: 
publisher:  opt-nc/template-eae
rights: © 2022 opt-nc/template-eae, CC BY-NC
stylesheet: epub.css
cover-image: cover.jpg
...
```
